### ISSUE TITLE
Cannot run using python 3.9 because of type annotations

### ISSUE THREAD

**Issue by GoGIGA** [CoolCat467/Scanner-Server#35]
Thank your for creating this project. It would be nice to have such a thing for my little office. I have installed pip, git, ... on my pi3 and installed afterwards your webserver. When running the software the foloowing errors are shown:
/usr/local/lib/python3.9/dist-packages/quart_trio/app.py:165: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
  self, error: Union[Exception, trio.MultiError]
Traceback (most recent call last):
  File "/usr/local/bin/sanescansrv", line 5, in <module>
    from sanescansrv import run
  File "/usr/local/lib/python3.9/dist-packages/sanescansrv/__init__.py", line 1, in <module>
    from sanescansrv.server import (
  File "/usr/local/lib/python3.9/dist-packages/sanescansrv/server.py", line 47, in <module>
    from sanescansrv import htmlgen, logger
  File "/usr/local/lib/python3.9/dist-packages/sanescansrv/htmlgen.py", line 20, in <module>
    TagArg = str | int | float | bool
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Is there a walkaround

Have a nice day

Rainer

**Comment by CoolCat467** [comment]
Ah, I think this is a result of running it with python 3.9. I have only been testing it in python 3.11, but I think I've made a few changes that might make this work properly, otherwise I'll change the install requirements to require newer versions of python.

**Comment by CoolCat467** [comment]
This issue should be fixed as of 97b9534, please re-open this issue if any more problems arise.
